### ISSUE TITLE
Token

### ISSUE THREAD

**Issue by MikeRund** [dwyl/phoenix-liveview-calculator#4]
GitHub actions is asking for an access token but it doesn't seem I have the permission to add that to this repo. 

Should I send that to you directly @nelsonic? 🤔

**Comment by nelsonic** [comment]
Let’s pair on it. 👌
Come to my desk when you are free. 👨‍💻

**Comment by asntc** [comment]
https://github.com/dwyl/phoenix-liveview-calculator/settings/secrets/actions

<img width="519" alt="image" src="https://github.com/user-attachments/assets/88d31b97-e018-4f96-810d-ecbf406b431b">

deploy fropom github ci working. ✅

**Comment by nelsonic** [comment]
@MikeRund please make sure you've understood how this was done and then close. ✅

**Comment by MikeRund** [comment]
Just cemented the pair programming knowledge with further reading of [CD w/ FLy.io & GitHub actions](https://fly.io/docs/launch/continuous-deployment-with-github-actions/)
and [workflow basics](https://docs.github.com/en/actions/writing-workflows/about-workflows) 💭

**Comment by nelsonic** [comment]
Nice one. 👌 
As long as you are confident you can deploy solo, all good. 🥷
