### ISSUE TITLE
UI issues 

### ISSUE THREAD

**Issue by MikeRund** [dwyl/phoenix-liveview-calculator#6]
In the tailwind playground the current UI fits the screen and is responsive (while still in need of polish):

![image](https://github.com/user-attachments/assets/eceac065-7b6a-4d7e-a24e-640df9f1000b)

But on the web page there is empty space on the top, left and bottom of the UI

![image](https://github.com/user-attachments/assets/944bc44e-290e-4209-abb9-14a720472587)

Investigating.

I'm wondering if it's to something to do with how LiveView contains its views 🤔

**Comment by MikeRund** [comment]
Found the cause of the padding:

![image](https://github.com/user-attachments/assets/03fc6284-3a00-41c2-8311-7f59e55cb48e)

**Comment by MikeRund** [comment]
Fixed for larger screens:

![image](https://github.com/user-attachments/assets/ff29ff3e-2f2d-41cd-a161-f04848b5392f)

And smaller / mobile screens:

![image](https://github.com/user-attachments/assets/ceacafc1-0921-4183-a3b0-ffb73f374461)

Issues were caused by:
- margins combined with h-screen caused additional space to be taken
- for smaller screens needed `flex-1` on the calc and history for equal spacing 
- excessive h-full may have been causing conflicts

**Comment by nelsonic** [comment]
Good forensic detective work. 🕵️ 🔍 👌
