### ISSUE TITLE
Unexpected payment from Fly.io

### ISSUE THREAD

**Issue by MikeRund** [dwyl/phoenix-liveview-calculator#7]
Woke up to a lovely invoice from Fly.io

![image](https://github.com/user-attachments/assets/26c66073-625c-4693-a357-841fa96ab600)

This would be left over from when I deployed on my own account instead of Dwyl's. 🥴 

I've removed my payment method now, if I delete the individual account I set up would I still have access to the Dwyl one?

**Comment by nelsonic** [comment]
Painful. 😢

**Comment by iteles** [comment]
Reimbursed this, let me know if the extra foreign currency charges were more than I sent through!

**Comment by MikeRund** [comment]
Thanks Ines!

**Comment by nelsonic** [comment]
Next time definitely deploy to an org @dwyl owns to avoid fees. 😉 

<img width="929" alt="image" src="https://github.com/user-attachments/assets/f2e1a523-04fe-4246-bbb3-74cace1c5b3d">
