### ISSUE TITLE
Streams issue 

### ISSUE THREAD

**Issue by MikeRund** [dwyl/phoenix-liveview-calculator#8]
For rendering the history tab I'm trying to use [streams](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#stream/4) which may be overkill for the small project. Running into the current issue:

![image](https://github.com/user-attachments/assets/9820dcaf-24ad-4e9d-9033-82274b4d5132)

The mount:

```elixir
 def mount(_params, _session, socket) do
    history =
      stream(socket, :calcs, [%{id: 0, string: "No history"}])

    socket = assign(socket, calc: "", mode: "", history: history)
    {:ok, socket}
  end

```
The update function:

```elixir
 defp updateHistory(socket) do
    string = socket.assigns.calc
    stream_insert(socket, :calcs, %Calc{id: 1, string: string})
    {:ok, socket}
  end
```

And the HEEx:

```html
 <ul id="calc-stream" phx-update="stream">
  <li :for={{calc_id, calculation} <- @streams.calcs} id={calc_id}>
    <%= calculation.string %>
  </li>
</ul>
```

**Comment by MikeRund** [comment]
I was calling `stream/4` wrong and trying to save it in the `history` variable, even after the following change:
```elixir
 socket = assign(socket, calc: "", mode: "")

    socket =
      stream(socket, :calcs, [%{id: 0, string: "No history"}])
```

the error still persists

**Comment by MikeRund** [comment]
By removing the relevant HEEx and adding `dbg/2` to the code the streams appears to be initialized correctly:

![image](https://github.com/user-attachments/assets/ca204d58-d06d-41f8-9e8e-0b0d9693a578)

Issue appears to be with HEEx code being unable to find the `streams` map 🤔

**Comment by MikeRund** [comment]
As the error code mentions the inner block slot 

![image](https://github.com/user-attachments/assets/4911ec18-14c5-4922-9f42-0e3adaee5737)

I thought there might be an issue accessing the special `@streams` assigns from the core component, but when moving the HEEx that is attempting to render the stream out of the core component and into the LiveView's `render/1` function nothing changes.

```elixir

 def render(assigns) do
    ~H"""
      <.calculator><%= @calc %></.calculator>
      <!-- History -->
      <div class="flex min-h-screen flex-1 flex-col bg-gray-600 p-4">
        <div class="mb-4 flex h-32 items-end justify-end rounded-lg
        bg-gray-800 font-mono text-6xl text-white">
          <div class="mr-4">

            <ul id="calc-stream" phx-update="stream">
              <li :for={{dom_id, calculation} <- @streams.calcs} id={dom_id}>
                <%= calculation.string %>
              </li>
            </ul>

          </div>
        </div>
        <!-- Additional History content -->
      </div>
    """
```

**Comment by asntc** [comment]
there i fixed it for you. ✅ 

![image](https://github.com/user-attachments/assets/17a5524a-9b20-453a-adba-3d80d6632922)
